version: '3.8'

services:
  api:
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: cifra-api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/opt/app/
    ports:
      - "8000:8000"
    depends_on:
      - cifra-db
  
  db:
    image: postgres
    container_name: cifra-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
