# Generated by Django 5.1 on 2025-04-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priceproducthistory',
            options={'ordering': ['price'], 'verbose_name': 'Histórico de preço de produto', 'verbose_name_plural': 'Históricos de preço de produto'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['price'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AddField(
            model_name='category',
            name='svg',
            field=models.TextField(blank=True, null=True, verbose_name='SVG'),
        ),
    ]
