# Generated by Django 5.1 on 2025-05-01 15:30

import features.stores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_priceproducthistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=10, verbose_name='Quantidade disponível'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='priceproducthistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=features.stores.models.product_directory_path, verbose_name='Imagem'),
        ),
    ]
