# Generated by Django 5.1 on 2025-05-11 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priceproducthistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Histórico de preço de produto', 'verbose_name_plural': 'Históricos de preço de produto'},
        ),
        migrations.CreateModel(
            name='ProductTechnicalCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(verbose_name='Nome da Característica')),
                ('value', models.CharField(verbose_name='Característica')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='stores.product')),
            ],
            options={
                'verbose_name': 'Caracteristica Técnica do Produto',
                'verbose_name_plural': 'Caracteristicas Técnicas do Produto',
            },
        ),
    ]
