# Generated by Django 5.1 on 2025-05-18 15:46

import core.validators.cnpj_validator
import django.db.models.deletion
import features.user.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_alter_priceproducthistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(default='Rua Cardoso, 8\nVila Independencia 3ª Seção\n21918-620 Cavalcanti de da Luz / TO', max_length=256, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='store',
            name='cnpj',
            field=models.CharField(default='95.278.613/0001-00', max_length=18, validators=[core.validators.cnpj_validator.CNPJValidator()], verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='store',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL, validators=[features.user.validators.validate_logistic], verbose_name='Loja'),
        ),
    ]
