# Generated by Django 5.1 on 2025-05-25 15:33

import core.validators.cnpj_validator
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_remove_product_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Unidade', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(default='Parque Daniela Cunha, 335\nConjunto Novo Dom Bosco\n81223695 Teixeira / RS', max_length=256, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='store',
            name='cnpj',
            field=models.CharField(default='61.928.047/0001-04', max_length=18, validators=[core.validators.cnpj_validator.CNPJValidator()], verbose_name='CNPJ'),
        ),
    ]
