# Generated by Django 5.1 on 2025-05-29 19:58

import core.validators.cnpj_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_alter_product_price_alter_store_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(default='Via Luiz Miguel Rocha, 67\nBairro Das Indústrias Ii\n77387216 Silveira / SP', max_length=256, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='store',
            name='cnpj',
            field=models.CharField(default='87.104.392/0001-17', max_length=18, validators=[core.validators.cnpj_validator.CNPJValidator()], verbose_name='CNPJ'),
        ),
    ]
