# Generated by Django 5.1 on 2025-05-29 20:45

import core.validators.cnpj_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_alter_store_address_alter_store_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(default='Favela de Freitas, 731\nSagrada Família\n17912-063 da Mata das Flores / GO', max_length=256, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='store',
            name='cnpj',
            field=models.CharField(default='96.015.372/0001-60', max_length=18, validators=[core.validators.cnpj_validator.CNPJValidator()], verbose_name='CNPJ'),
        ),
    ]
