# Generated by Django 4.2.3 on 2024-07-25 19:32

import core.validators.postal_code
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=9, validators=[core.validators.postal_code.PostalCodeValidator()], verbose_name='CEP')),
                ('street', models.CharField(max_length=160, verbose_name='Rua')),
                ('district', models.CharField(max_length=160, verbose_name='Bairro')),
                ('city', models.CharField(max_length=160, verbose_name='Cidade')),
                ('state', models.CharField(choices=[('RO', 'RO'), ('AC', 'AC'), ('AM', 'AM'), ('RR', 'RR'), ('PA', 'PA'), ('AP', 'AP'), ('TO', 'TO'), ('MA', 'MA'), ('PI', 'PI'), ('CE', 'CE'), ('RN', 'RN'), ('PB', 'PB'), ('PE', 'PE'), ('AL', 'AL'), ('SE', 'SE'), ('BA', 'BA'), ('MG', 'MG'), ('ES', 'ES'), ('RJ', 'RJ'), ('SP', 'SP'), ('PR', 'PR'), ('SC', 'SC'), ('RS', 'RS'), ('MS', 'MS'), ('MT', 'MT'), ('GO', 'GO'), ('DF', 'DF')], max_length=2, verbose_name='UF')),
                ('number', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Número')),
                ('complement', models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='Complemento')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
    ]
