# Generated by Django 4.2.3 on 2024-11-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construtor', models.CharField(max_length=200, verbose_name='Construtora')),
                ('name', models.CharField(max_length=500, verbose_name='Nome do Produto')),
                ('price', models.FloatField(verbose_name='Preço do produto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
