# Generated by Django 5.1 on 2025-05-25 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0007_alter_product_price_alter_store_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nome')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, help_text='Valor total dos produtos do melhor local de compra', max_digits=12, null=True, verbose_name='Preço total')),
                ('last_update', models.DateTimeField(blank=True, null=True, verbose_name='Última atualização')),
                ('better_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store', verbose_name='Melhor Loja')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Lista de Usuário',
                'verbose_name_plural': 'Listas de Usuários',
            },
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Quantidade de itens')),
                ('user_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='lists.userlist', verbose_name='Lista')),
            ],
        ),
    ]
