# Generated by Django 5.1 on 2025-06-04 16:57

import features.lists.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_productlist_price_productlist_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=features.lists.models.product_directory_path, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor do produto no melhor local de compra', max_digits=12, null=True, verbose_name='Preço'),
        ),
    ]
