# Generated by Django 5.1 on 2025-04-02 22:44

from django.db import migrations


def create_admin_account(apps, s):
    User = apps.get_model("user", "User")
    User.objects.create_superuser(
        email="admin@admin.com",
        password="admin"
    )
    
    print("Usuário admin criado")

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin_account)
    ]
