# Generated by Django 5.1 on 2025-04-03 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20250402_1944'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserForgotPasswordToken',
        ),
    ]
