# Generated by Django 5.1 on 2025-05-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_userforgotpasswordtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_user',
            field=models.CharField(default='client', max_length=8, verbose_name='Tipo de Usuário'),
        ),
    ]
